using UnityEngine;
using System;
using System.Collections;

public class MonsterHealth : MonoBehaviour
{
    private MonsterBlackBoard blackBoard;
    
    [SerializeField] private float noDamageCooldown = 0.5f;
    private void Start()
    { 
        blackBoard = GetComponent<MonsterBlackBoard>();
    }

    void Update(){
        if(Input.GetKeyDown(KeyCode.Space)){
            TakeDamage(1000);
        }
    }
    public void TakeDamage(int damage)
    {
        if (blackBoard.isMonsterDamaged) return;      //ì¤‘ë³µ í”¼ê²© ë°©ì§€

        blackBoard.currentHP -= damage;
        
        blackBoard.isMonsterDamaged = true;
        blackBoard.OnHPChanged?.Invoke(blackBoard.currentHP);
        StartCoroutine(Coroutine_ResetDamageState());
    }


    public void HandleDamageAnim()
    {
        if (blackBoard.isMonsterDamaged && !blackBoard.animator.GetCurrentAnimatorStateInfo(0).IsName("Damaged"))              // ğŸ”¥ `isDamaged`ê°€ trueì´ë©´ ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰í•˜ë„ë¡ ìˆ˜ì •
        {
            blackBoard.animator.SetTrigger("Damaged");
        }   
    }

    IEnumerator Coroutine_ResetDamageState()
    {  
        yield return new WaitForSeconds(noDamageCooldown);
        blackBoard.isMonsterDamaged = false;
    }
}